### ISSUE TITLE
Your project includes an outdated version of Sarissa, which causes issue with later IE versions.

### ISSUE THREAD

**Issue by volkertb** [ColdTrick/pages_tree#1]
Hi!

I noticed that your current code base includes an outdated version of Sarissa (0.9.9.4). The latest official upstream release of Sarissa was 0.9.9.6, and it included some crucial fixes for IE9 compatibility, among other things.

However, even that version is outdated. I started a 0.9.9.7-SNAPSHOT branch on GitHub, which includes fixes from the latest CVS trunk from the upstream project.

If you are still maintaining this project, please considering upgrading Sarissa. you don't necessarily have to use my branch, but please consider at least upgrading to version 0.9.9.6 or the latest CVS trunk from upstream.

If you happen to have (or know of) any useful patches for Sarissa that have not yet made it upstream, I would be happy to have them committed to my branch! You can check out my Sarissa branch on GitHub here: https://github.com/volkertb/sarissa/tree/0.9.9.7-SNAPSHOT

Thanks for considering and keep on coding! :-)

**Comment by jdalsem** [comment]
Thanks for letting me know. However this plugin is longer maintained, so there will be no update
